### ISSUE TITLE
Installation instructions for MacOS

### ISSUE THREAD

**Issue by FoxMcWeezer** [blockfish/blockfish#4]
Having trouble at the part where I need to include SDL2, SDL2_tff dll files in the same directory. Not sure where to get these. Expert googler but couldn't figure this out. Also the windows version of the release exe is not launching anymore

**Comment by iitalics** [comment]
Neither of the released binaries will work on Mac OS. Mac computers are expensive and development on them is very obtuse. If somebody else with combined Rust + Mac knowledge would like to contribute a build then I will provide it but until then I'm not interested in supporting Mac.

**Comment by iitalics** [comment]
closed via #10
