### ISSUE TITLE
Outdated information in readme

### ISSUE THREAD

**Issue by chouhy** [blockfish/blockfish#7]
> Currently, Blockfish tends to outperform even highly skilled players, and has already [beaten](https://www.youtube.com/watch?v=jfOyigfLPCU) the [world record](https://jstris.jezevec10.com/replay/9274538) for least-pieces 100L cheese race.

The current world record for least-pieces 100L cheese race is now held by Qinghan's 185 pieces.
https://jstris.jezevec10.com/replay/54532835

**Comment by frey-mz** [comment]
Outdated blockfish world record.
The current world record for least-pieces 100L cheese race is now held by Blockfish's 174 pieces.
https://jstris.jezevec10.com/replay/53445238

**Comment by iitalics** [comment]
fixed in 6a2ace02bf1b239da8ebcf997ab11a9c63a28208, thanks for digging up these replays @chouhy @freyhoe
