### ISSUE TITLE
Ability to use NUMPAD numbers as part of control scheme

### ISSUE THREAD

**Issue by Zhuinden** [blockfish/blockfish#8]
I tried to set up "numpad 4" for rotation, "numpad 0" for soft drop etc (not my layout, but someone I know) however I found no way to actually set "numpad" in the control scheme.

`C-`  is parsed for CTRL, and I see that keys are parsed based on their number, but how to use `numpad`? I tried `num3`, `num-3`, `numpad3`, neither worked.

Thanks!

**Comment by iitalics** [comment]
Can you try e.g. "Keypad 3"? The key names originate from the SDL2 library and I believe that's the terminology they use.

**Comment by Zhuinden** [comment]
It works! Thank you ❤️
